# Generated by Django 2.1.7 on 2019-03-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other/Choose to not specify')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='need_accomodation',
            field=models.BooleanField(default=False),
        ),
    ]
