# Generated by Django 2.1.7 on 2019-03-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190308_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
